import { VehicleZone } from '@autobody/shared';

export const VEHICLE_ZONES_CONFIG: VehicleZone[] = [
  // ─── VISTA SUPERIOR ───
  {
    id: 'techo',
    label: 'Techo',
    view: 'top',
    subcomponents: [
      { id: 'panel-techo', label: 'Panel exterior del techo' },
      { id: 'riel-techo-izq', label: 'Riel izquierdo' },
      { id: 'riel-techo-der', label: 'Riel derecho' },
      { id: 'luz-techo', label: 'Luz interior de techo' },
      { id: 'aislante-techo', label: 'Aislante acústico' },
      { id: 'tapiz-techo', label: 'Tapizado interior de techo' },
    ],
  },
  {
    id: 'capo',
    label: 'Capó',
    view: 'top',
    subcomponents: [
      { id: 'panel-capo', label: 'Panel exterior del capó' },
      { id: 'refuerzo-capo', label: 'Refuerzo interno' },
      { id: 'bisagra-capo-izq', label: 'Bisagra izquierda' },
      { id: 'bisagra-capo-der', label: 'Bisagra derecha' },
      { id: 'seguro-capo', label: 'Seguro / Pestillo' },
      { id: 'aislante-capo', label: 'Aislante acústico/térmico' },
    ],
  },
  {
    id: 'maletero',
    label: 'Maletero / Cajuela',
    view: 'top',
    subcomponents: [
      { id: 'panel-maletero', label: 'Panel exterior del maletero' },
      { id: 'refuerzo-maletero', label: 'Refuerzo interno' },
      { id: 'bisagra-maletero-izq', label: 'Bisagra izquierda' },
      { id: 'bisagra-maletero-der', label: 'Bisagra derecha' },
      { id: 'cerradura-maletero', label: 'Cerradura / Cerrojo' },
      { id: 'moldura-maletero', label: 'Moldura perimetral' },
      { id: 'emblema-trasero', label: 'Emblema / Logo trasero' },
    ],
  },
  {
    id: 'puerta-del-izq',
    label: 'Puerta Delantera Izquierda (Piloto)',
    view: 'top',
    subcomponents: [
      { id: 'panel-ext-pdi', label: 'Panel exterior de puerta' },
      { id: 'marco-pdi', label: 'Marco / Moldura de puerta' },
      { id: 'manija-ext-pdi', label: 'Manija exterior' },
      { id: 'manija-int-pdi', label: 'Manija interior' },
      { id: 'vidrio-pdi', label: 'Vidrio / Luna' },
      { id: 'elevador-pdi', label: 'Mecanismo elevador de luna' },
      { id: 'bisagra-sup-pdi', label: 'Bisagra superior' },
      { id: 'bisagra-inf-pdi', label: 'Bisagra inferior' },
      { id: 'cerradura-pdi', label: 'Cerradura / Chapas' },
      { id: 'tapizado-pdi', label: 'Tapizado interior' },
      { id: 'espejo-pdi', label: 'Espejo retrovisor lateral' },
      { id: 'burletes-pdi', label: 'Sellado / Burletes' },
    ],
  },
  {
    id: 'puerta-del-der',
    label: 'Puerta Delantera Derecha (Copiloto)',
    view: 'top',
    subcomponents: [
      { id: 'panel-ext-pdd', label: 'Panel exterior de puerta' },
      { id: 'marco-pdd', label: 'Marco / Moldura de puerta' },
      { id: 'manija-ext-pdd', label: 'Manija exterior' },
      { id: 'manija-int-pdd', label: 'Manija interior' },
      { id: 'vidrio-pdd', label: 'Vidrio / Luna' },
      { id: 'elevador-pdd', label: 'Mecanismo elevador de luna' },
      { id: 'bisagra-sup-pdd', label: 'Bisagra superior' },
      { id: 'bisagra-inf-pdd', label: 'Bisagra inferior' },
      { id: 'cerradura-pdd', label: 'Cerradura / Chapas' },
      { id: 'tapizado-pdd', label: 'Tapizado interior' },
      { id: 'espejo-pdd', label: 'Espejo retrovisor lateral' },
      { id: 'burletes-pdd', label: 'Sellado / Burletes' },
    ],
  },
  {
    id: 'puerta-tra-izq',
    label: 'Puerta Trasera Izquierda',
    view: 'top',
    subcomponents: [
      { id: 'panel-ext-pti', label: 'Panel exterior de puerta' },
      { id: 'marco-pti', label: 'Marco / Moldura de puerta' },
      { id: 'manija-ext-pti', label: 'Manija exterior' },
      { id: 'manija-int-pti', label: 'Manija interior' },
      { id: 'vidrio-pti', label: 'Vidrio / Luna' },
      { id: 'elevador-pti', label: 'Mecanismo elevador de luna' },
      { id: 'bisagra-sup-pti', label: 'Bisagra superior' },
      { id: 'bisagra-inf-pti', label: 'Bisagra inferior' },
      { id: 'cerradura-pti', label: 'Cerradura / Chapas' },
      { id: 'tapizado-pti', label: 'Tapizado interior' },
      { id: 'burletes-pti', label: 'Sellado / Burletes' },
    ],
  },
  {
    id: 'puerta-tra-der',
    label: 'Puerta Trasera Derecha',
    view: 'top',
    subcomponents: [
      { id: 'panel-ext-ptd', label: 'Panel exterior de puerta' },
      { id: 'marco-ptd', label: 'Marco / Moldura de puerta' },
      { id: 'manija-ext-ptd', label: 'Manija exterior' },
      { id: 'manija-int-ptd', label: 'Manija interior' },
      { id: 'vidrio-ptd', label: 'Vidrio / Luna' },
      { id: 'elevador-ptd', label: 'Mecanismo elevador de luna' },
      { id: 'bisagra-sup-ptd', label: 'Bisagra superior' },
      { id: 'bisagra-inf-ptd', label: 'Bisagra inferior' },
      { id: 'cerradura-ptd', label: 'Cerradura / Chapas' },
      { id: 'tapizado-ptd', label: 'Tapizado interior' },
      { id: 'burletes-ptd', label: 'Sellado / Burletes' },
    ],
  },
  {
    id: 'aleta-del-izq',
    label: 'Aleta Delantera Izquierda',
    view: 'top',
    subcomponents: [
      { id: 'panel-aleta-di', label: 'Panel exterior de aleta' },
      { id: 'moldura-aleta-di', label: 'Moldura / Protector' },
      { id: 'emblema-aleta-di', label: 'Emblema lateral' },
      { id: 'pasaruedas-di', label: 'Guardabarros / Pasaruedas' },
    ],
  },
  {
    id: 'aleta-del-der',
    label: 'Aleta Delantera Derecha',
    view: 'top',
    subcomponents: [
      { id: 'panel-aleta-dd', label: 'Panel exterior de aleta' },
      { id: 'moldura-aleta-dd', label: 'Moldura / Protector' },
      { id: 'emblema-aleta-dd', label: 'Emblema lateral' },
      { id: 'pasaruedas-dd', label: 'Guardabarros / Pasaruedas' },
    ],
  },
  {
    id: 'aleta-tra-izq',
    label: 'Aleta Trasera Izquierda',
    view: 'top',
    subcomponents: [
      { id: 'panel-aleta-ti', label: 'Panel exterior de aleta' },
      { id: 'moldura-aleta-ti', label: 'Moldura / Protector' },
      { id: 'pasaruedas-ti', label: 'Guardabarros / Pasaruedas' },
    ],
  },
  {
    id: 'aleta-tra-der',
    label: 'Aleta Trasera Derecha',
    view: 'top',
    subcomponents: [
      { id: 'panel-aleta-td', label: 'Panel exterior de aleta' },
      { id: 'moldura-aleta-td', label: 'Moldura / Protector' },
      { id: 'pasaruedas-td', label: 'Guardabarros / Pasaruedas' },
    ],
  },

  // ─── VISTA FRONTAL ───
  {
    id: 'bumper-del',
    label: 'Parachoque Delantero',
    view: 'front',
    subcomponents: [
      { id: 'cuerpo-bumper-del', label: 'Cuerpo principal del bumper' },
      { id: 'spoiler-del', label: 'Spoiler inferior / Respón' },
      { id: 'moldura-bumper-del-izq', label: 'Moldura izquierda' },
      { id: 'moldura-bumper-del-der', label: 'Moldura derecha' },
      { id: 'soporte-bumper-del', label: 'Soporte interno (refuerzo)' },
      { id: 'rejilla-bumper-del', label: 'Rejilla integrada' },
      { id: 'sensor-park-del', label: 'Sensor de aparcamiento' },
      { id: 'emblema-frontal', label: 'Emblema / Logo frontal' },
    ],
  },
  {
    id: 'grille',
    label: 'Rejilla / Parrilla (Grille)',
    view: 'front',
    subcomponents: [
      { id: 'grille-central', label: 'Rejilla central' },
      { id: 'grille-inferior', label: 'Rejilla inferior' },
      { id: 'moldura-grille', label: 'Marco / Moldura de rejilla' },
    ],
  },
  {
    id: 'faro-del-izq',
    label: 'Faro Delantero Izquierdo',
    view: 'front',
    subcomponents: [
      { id: 'conjunto-faro-di', label: 'Conjunto de faro completo' },
      { id: 'lente-faro-di', label: 'Lente / Cristal' },
      { id: 'carcasa-faro-di', label: 'Carcasa / Housing' },
      { id: 'bombilla-di', label: 'Bombilla / Módulo LED' },
      { id: 'soporte-faro-di', label: 'Soporte de montaje' },
    ],
  },
  {
    id: 'faro-del-der',
    label: 'Faro Delantero Derecho',
    view: 'front',
    subcomponents: [
      { id: 'conjunto-faro-dd', label: 'Conjunto de faro completo' },
      { id: 'lente-faro-dd', label: 'Lente / Cristal' },
      { id: 'carcasa-faro-dd', label: 'Carcasa / Housing' },
      { id: 'bombilla-dd', label: 'Bombilla / Módulo LED' },
      { id: 'soporte-faro-dd', label: 'Soporte de montaje' },
    ],
  },
  {
    id: 'espejo-izq',
    label: 'Espejo Retrovisor Izquierdo',
    view: 'front',
    subcomponents: [
      { id: 'carcasa-espejo-izq', label: 'Carcasa exterior' },
      { id: 'luna-espejo-izq', label: 'Luna del espejo' },
      { id: 'motor-espejo-izq', label: 'Motor de ajuste eléctrico' },
      { id: 'base-espejo-izq', label: 'Base de montaje' },
    ],
  },
  {
    id: 'espejo-der',
    label: 'Espejo Retrovisor Derecho',
    view: 'front',
    subcomponents: [
      { id: 'carcasa-espejo-der', label: 'Carcasa exterior' },
      { id: 'luna-espejo-der', label: 'Luna del espejo' },
      { id: 'motor-espejo-der', label: 'Motor de ajuste eléctrico' },
      { id: 'base-espejo-der', label: 'Base de montaje' },
    ],
  },

  // ─── VISTA TRASERA ───
  {
    id: 'bumper-tra',
    label: 'Parachoque Trasero',
    view: 'rear',
    subcomponents: [
      { id: 'cuerpo-bumper-tra', label: 'Cuerpo principal del bumper' },
      { id: 'spoiler-tra', label: 'Spoiler inferior' },
      { id: 'moldura-bumper-tra-izq', label: 'Moldura izquierda' },
      { id: 'moldura-bumper-tra-der', label: 'Moldura derecha' },
      { id: 'soporte-bumper-tra', label: 'Soporte interno (refuerzo)' },
      { id: 'sensor-park-tra', label: 'Sensor de aparcamiento' },
      { id: 'camara-tra', label: 'Cámara de retroceso' },
    ],
  },
  {
    id: 'faro-tra-izq',
    label: 'Faro Trasero Izquierdo',
    view: 'rear',
    subcomponents: [
      { id: 'conjunto-faro-ti', label: 'Conjunto de faro trasero completo' },
      { id: 'lente-faro-ti', label: 'Lente / Cristal' },
      { id: 'carcasa-faro-ti', label: 'Carcasa / Housing' },
      { id: 'soporte-faro-ti', label: 'Soporte de montaje' },
    ],
  },
  {
    id: 'faro-tra-der',
    label: 'Faro Trasero Derecho',
    view: 'rear',
    subcomponents: [
      { id: 'conjunto-faro-td', label: 'Conjunto de faro trasero completo' },
      { id: 'lente-faro-td', label: 'Lente / Cristal' },
      { id: 'carcasa-faro-td', label: 'Carcasa / Housing' },
      { id: 'soporte-faro-td', label: 'Soporte de montaje' },
    ],
  },
];

export const ZONE_BY_ID = Object.fromEntries(VEHICLE_ZONES_CONFIG.map(z => [z.id, z]));
export const ZONES_BY_VIEW = {
  top: VEHICLE_ZONES_CONFIG.filter(z => z.view === 'top'),
  front: VEHICLE_ZONES_CONFIG.filter(z => z.view === 'front'),
  rear: VEHICLE_ZONES_CONFIG.filter(z => z.view === 'rear'),
};
